chat bot code
atlp-rwanda/trojans-ec-bn pull request #107
Opened 2023-02-28 07:04 UTC by Marthatwesi

### What does this PR do?

Users should be able to chat on e-commerce to ask some information publicly

### Description of Task to be completed?

Having travellers interacting with each other on the platform adds value to it as it allows them to asks questions about places, offer recommendations, guidance etc...

**Acceptance Criteria**

**GIVEN** the user is online
**WHEN** they open the chat tab
**THEN** they should be able to read all of the past chats

**GIVEN** the user is online
**WHEN** they open the chat tab
**THEN** they should be able to post a public chat

**GIVEN**the user
**WHEN** they post a chat
**THEN** it should be able to be echoed to all online users in realtime.

### How should this be manually tested?
 npm run test  or run the index.html in the public folder on live server 

### Any background context you want to provide?

N/A
### What are the relevant pivotal tracker stories?

https://www.pivotaltracker.com/n/projects/2628461/stories/184347116

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-28 07:06 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-28 07:39 UTC, NG-Solennel submitted a review, later dismissed

2023-02-28 07:53 UTC, Ntarecedrick approved these changes, later dismissed

2023-02-28 09:04 UTC, Eli250 requested changes

2023-02-28 09:04 UTC, Eli250 commented on src/public/script.js
> +const userName = prompt("What is your name?");
You don't need to prompt the user for their names, get all this info from their login session.

2023-02-28 09:04 UTC, Eli250 commented on src/public/script.js
> +const socket = io("http://localhost:3000", {
This socket URL should be in env, do not hardcode it.

2023-02-28 09:04 UTC, Eli250 commented on src/utils/socketio.js
> +export const cryptr = new Cryptr("myTotallySecretKey", {
Do not hardcode the key. Use `env`

2023-02-28 15:17 UTC, UwaweTera submitted a review, later dismissed

2023-03-02 10:59 UTC, NG-Solennel approved these changes, later dismissed

2023-03-02 11:01 UTC, Ntarecedrick approved these changes, later dismissed

2023-03-02 11:03 UTC, UwaweTera submitted a review, later dismissed

2023-03-02 11:38 UTC, Eli250 requested changes

2023-03-02 11:38 UTC, Eli250 commented on package.json
> +    "chat": "jest --testPathPattern=‘chatbot.test.js’  --forceExit --collect-coverage"
When do we need this script?

2023-03-02 11:38 UTC, Eli250 commented on src/database/migrations/20230217122520-create-message.js
> +      name: {
You don't need this field since you have the user id.

2023-03-02 11:38 UTC, Eli250 commented on src/database/models/message.js
> +      name: DataTypes.STRING,
What's the use of this field?

2023-03-02 11:38 UTC, Eli250 commented on src/database/seeders/20230302074002-message.js
> +          name: "testBuyer",
The name is not needed here

2023-03-02 11:38 UTC, Eli250 commented on src/routes/api/chat.route.js
> +  checkRole(["admin"]),
Only admin is allowed to recive all chats? How about the rest of users?

2023-03-02 11:38 UTC, Eli250 commented on src/utils/socketio.js
> +const userExists = (token, next) => {
We already have a middleware that checks this, why did you write it again?

2023-03-02 19:01 UTC, NG-Solennel approved these changes

2023-03-02 19:02 UTC, Ntarecedrick approved these changes

2023-03-02 19:24 UTC, UwaweTera approved these changes

2023-03-03 09:22 UTC, Eli250 approved these changes

2023-03-03 09:24 UTC, merged