payment integration
atlp-rwanda/trojans-ec-bn pull request #111
Opened 2023-03-06 13:13 UTC by teerenzo

### What does this PR do?

This PR intend to allow buyer to make payment 

### Description of Task to be completed?

User will be able to make payment after successfully payment, cart will be cleared and User will be able to see ordered products

### How should this be manually tested?

you can test manual by using provided end point on docs

### Any background context you want to provide?

Any other information you can give about the task.

### What are the relevant pivotal tracker stories?

https://www.pivotaltracker.com/story/show/184347109

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] My code is formatted correctly
- [x] My changes doesn't have any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-06 13:59 UTC, denislohan requested changes
1. Your PR is named wrong
2. your commit is named wrong

2023-03-06 14:18 UTC, Eli250 requested changes

2023-03-06 14:18 UTC, Eli250 commented on src/controllers/paymentController.js
> +  static async success(req, res) {
The naming of these functions is not clear. You have to follow conventions.

2023-03-06 14:18 UTC, Eli250 commented on src/routes/api/payment.route.js
> +route.get("/success",PaymentController.success)
These routes have no meaning. Use something everyone can understand

2023-03-06 14:18 UTC, Eli250 commented on src/services/paymentService.js
> +      const lineItems = [];
What is lineItems? Use a self-explanatory variable.

2023-03-06 14:18 UTC, Eli250 commented on src/services/paymentService.js
> +    console.log(appUrl);
Remove this console.

2023-03-07 12:57 UTC, Eli250 approved these changes

2023-03-07 12:57 UTC, Eli250 commented on src/routes/api/product.route.js
> +  "/all/productWishes",
This endpoint does not make sense

2023-03-07 13:04 UTC, Ntarecedrick approved these changes

2023-03-07 13:05 UTC, NG-Solennel approved these changes

2023-03-08 11:15 UTC, merged