Ch setup swagger 184347080
atlp-rwanda/trojans-ec-bn pull request #58
Opened 2023-02-01 14:40 UTC by suave990

### What does this PR do?

setting up the swagger

### Description of Task to be completed?

setting up the swagger

### How should this be manually tested?

npm start

### Any background context you want to provide?

none

### What are the relevant pivotal tracker stories?

Setup API documentation using swagger
https://www.pivotaltracker.com/n/projects/2628461/184347080

### Screenshots (if appropriate)
n/a

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-01 14:46 UTC, Ntarecedrick commented
you can try and squash the commits to make it one

2023-02-01 14:48 UTC, Ntarecedrick reviewed
you should try to squash the commits and try to merge with dev instead of main

2023-02-01 21:10 UTC, Eli250 requested changes

2023-02-01 21:10 UTC, Eli250 commented on src/documentation/index.js
> +        url:"http://localhost:3003"
Do not hardcode the url. Use env

2023-02-02 17:46 UTC, Eli250 approved these changes

2023-02-02 17:47 UTC, Ntarecedrick approved these changes

2023-02-02 17:52 UTC, UwaweTera approved these changes

2023-02-02 17:54 UTC, Rutarenzi approved these changes

2023-02-02 17:55 UTC, merged