Ft user login 184347087
atlp-rwanda/trojans-ec-bn pull request #60
Opened 2023-02-02 14:07 UTC by UwaweTera

### What does this PR do?

User login with passport

### Description of Task to be completed?

This login user can make login and receive his/her name and token to use, when provided wrong data they can accept it

### How should this be manually tested?

```
  npm install 
  npm start
```
### Any background context you want to provide?

none

### What are the relevant pivotal tracker stories?

https://www.pivotaltracker.com/n/projects/2628461/184347087

### Screenshots (if appropriate)

<img width="897" alt="login prof" src="https://user-images.githubusercontent.com/112135715/216346583-17da2d9d-8915-4660-9449-f8f980c7d435.png">

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-02 19:17 UTC, Rutarenzi approved these changes

2023-02-03 05:58 UTC, NG-Solennel approved these changes

2023-02-03 07:30 UTC, NG-Solennel approved these changes

2023-02-03 07:53 UTC, Eli250 requested changes

2023-02-03 07:53 UTC, Eli250 commented on .env.example
>  DATABASE_PASSWORD=password
Remove values to these variables.
Eg: DATABASE_PASSWORD=
      PRODUCTION_DATABASE=
      JWT_SECRET=

2023-02-03 07:53 UTC, Eli250 commented on src/controllers/userController.js
> +    const user = {
Use object destructuring here

2023-02-03 07:53 UTC, Eli250 commented on src/validation/user.vald.js
> +const userVald = async (req, res, next) => {
Use meaningful variable name

2023-02-03 08:02 UTC, Eli250 requested changes
Resolve all addressed issues

2023-02-03 11:39 UTC, Eli250 requested changes

2023-02-03 11:39 UTC, Eli250 commented on .env.example
>  DATABASE_PASSWORD=password
Unassign these  variables too

2023-02-03 12:30 UTC, NG-Solennel commented
you have conflicts

2023-02-03 13:04 UTC, NG-Solennel approved these changes

2023-02-03 13:13 UTC, Eli250 approved these changes

2023-02-03 13:13 UTC, merged