refactored codes to add utils and services
atlp-rwanda/trojans-ec-bn pull request #73
Opened 2023-02-06 18:02 UTC by NG-Solennel

### What does this PR do?

Explain briefly the purspose of this PR

### Description of Task to be completed?

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### How should this be manually tested?

Provides steps on how this feature can tested.

### Any background context you want to provide?

Any other information you can give about the task.

### What are the relevant pivotal tracker stories?

Provide a relevant link to the pivotal tracker.

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-06 18:12 UTC, Ntarecedrick approved these changes

2023-02-06 18:21 UTC, Marthatwesi approved these changes

2023-02-06 18:28 UTC, Rutarenzi approved these changes

2023-02-07 08:27 UTC, Eli250 requested changes
Resolve comments

2023-02-07 08:27 UTC, Eli250 commented on src/controllers/userController.js
> +      return res.status(200).json({ user: response });
The response should always return the message and status

2023-02-07 08:27 UTC, Eli250 commented on src/controllers/userController.js
>        return res.status(500).json({ error });
Always return the structured message and status

2023-02-07 08:27 UTC, Eli250 commented on src/controllers/userController.js
> +      return res.status(201).send(response);
Your response should always be in json format and contains the message and status

2023-02-07 08:27 UTC, Eli250 commented on src/middlewares/alreadyExists.js
> +const alreadyExists = async (req, res, next) => {
Rename your middleware to "verifyUser.js"

2023-02-07 08:27 UTC, Eli250 commented on src/middlewares/alreadyExists.js
> +    return res.status(409).send("Email Already Exists");
The response should be in json format with both status and formatted message

2023-02-07 08:27 UTC, Eli250 commented on src/middlewares/index.js
> -// middleware function belong here
If  you no longer need this file get rid of it.

2023-02-07 08:27 UTC, Eli250 commented on src/middlewares/passport.js
> +import passport from "passport";
This is a utility component, not a middleware. Move it to utils directory and call it in your controller

2023-02-07 08:27 UTC, Eli250 commented on src/routes/api/user.route.js
> +  alreadyExists,
Rename this to verifyUser

2023-02-07 08:27 UTC, Eli250 commented on src/utils/index.js
> -// files with dependencies to use
Get rid of this file if you no longer need it.

2023-02-07 10:06 UTC, Eli250 approved these changes

2023-02-07 10:07 UTC, merged