#184347091 Profile Page Settings
atlp-rwanda/trojans-ec-bn pull request #77
Opened 2023-02-09 08:05 UTC by jimmymut

…oute for profile settings

### What does this PR do?

This PR is concerned with the profile page settings where the user registers and the profile is created and can update some profile information.

### Description of Task to be completed?

Profiles will provide a way to maintain generic and user specific data/info,Personal Information name, email, gender, birthdate,
preferred language, preferred currency
,where you live,Billing Adress

### How should this be manually tested?

This is tested when a user signs up or upadates the profile

### Any background context you want to provide?

N/A

### What are the relevant pivotal tracker stories?

[Provide a relevant link to the pivotal tracker.](https://www.pivotaltracker.com/story/show/184347091)

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-14 11:30 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-14 11:45 UTC, Rutarenzi approved these changes

2023-02-15 03:52 UTC, Ntarecedrick approved these changes

2023-02-15 05:22 UTC, teerenzo requested changes
Make sure that all test are passing

2023-02-15 10:51 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-15 11:01 UTC, NG-Solennel submitted a review, later dismissed

2023-02-15 11:11 UTC, NG-Solennel approved these changes

2023-02-15 11:32 UTC, Eli250 approved these changes

2023-02-15 11:32 UTC, merged