#184347086 Logout Functionality
atlp-rwanda/trojans-ec-bn pull request #86
Opened 2023-02-10 15:10 UTC by Rutarenzi

### What does this PR do?

Users should be able to log out of the application

### Description of Task to be completed?

When a user clicks on the logout link, they should be signed out of the application with their session ended

### How should this be manually tested?

You have to log in and get the token then after you log out

### Any background context you want to provide?

Given that we are dealing with API, upon user logout, we blacklist the token 

### What are the relevant pivotal tracker stories?

[Provide a relevant link to the pivotal tracke](https://www.pivotaltracker.com/story/show/184347086)r.

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code is formatted correctly
- [ ] My changes doesn't have any errors or warnings
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-13 05:47 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-14 07:38 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-14 08:41 UTC, suave990 approved these changes

2023-02-14 09:04 UTC, jimmymut submitted a review, later dismissed

2023-02-14 12:07 UTC, jimmymut submitted a review, later dismissed

2023-02-14 12:21 UTC, teerenzo submitted a review, later dismissed

2023-02-14 12:49 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-14 12:51 UTC, suave990 approved these changes
you may add up your test to increase %

2023-02-14 12:57 UTC, Eli250 requested changes

2023-02-14 12:57 UTC, Eli250 commented on .gitignore
> +checkToken.js
Why is this file here?

2023-02-14 14:00 UTC, Eli250 approved these changes

2023-02-14 14:01 UTC, merged