#184347101 ft-wishList
atlp-rwanda/trojans-ec-bn pull request #98
Opened 2023-02-17 08:25 UTC by teerenzo

### What does this PR do?

A buyer should be able to add a product to wish list

### Description of Task to be completed?

User will be able to add or remove product to wishList 

### How should this be manually tested?

using Swagger documentation

### Any background context you want to provide?

none

### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/184347101

### Screenshots (if appropriate)

### Questions:

# Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code is formatted correctly
- [x] My changes doesn't have any errors or warnings
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-02-17 08:32 UTC, UwaweTera submitted a review, later dismissed

2023-02-17 08:36 UTC, Ntarecedrick submitted a review, later dismissed

2023-02-17 08:38 UTC, jimmymut commented on src/controllers/wishListController.js
> +/* eslint-disable require-jsdoc */
These two lines can be one, /* eslint-disable valid-jsdoc, require-jsdoc */

2023-02-17 08:39 UTC, jimmymut commented on src/database/models/productwishes.js
> +/* eslint-disable require-jsdoc */
also here

2023-02-17 08:42 UTC, jimmymut commented on src/middlewares/checkUserExist.js
> +/* eslint-disable no-else-return */
Does this comment needed?

2023-02-17 08:42 UTC, Rutarenzi submitted a review, later dismissed

2023-02-17 08:44 UTC, jimmymut commented on src/middlewares/checkUserExist.js
> +/* eslint-disable no-else-return */
if it is, then combine both comments in one!

2023-02-17 08:46 UTC, jimmymut submitted a review, later dismissed

2023-02-17 09:41 UTC, iradukundairenee requested changes
1.please try looking at how you write your status code and  example on middleware/check productexist  file you use the status code 403 (forbidden) while you can use 404 (notfound)
also you on wishListController on line 10 you have used 200 which is not Good there you can use 201 (created)
https://medium.com/rtkal/http-response-status-codes-b78f273ac56e

2023-02-17 15:52 UTC, teerenzo commented on src/middlewares/checkUserExist.js
> +/* eslint-disable no-else-return */
yes I need it and how it is structured that is the best way for it to work

2023-02-20 05:46 UTC, iradukundairenee approved these changes, later dismissed

2023-02-20 06:15 UTC, UwaweTera approved these changes, later dismissed

2023-02-20 07:20 UTC, Ntarecedrick approved these changes, later dismissed

2023-02-20 08:22 UTC, Eli250 requested changes

2023-02-20 08:22 UTC, Eli250 commented on src/database/migrations/20230216073036-create-product-wishes.js
> +    await queryInterface.createTable('ProductWishes', {
Rename the model to `WishList` or `ProductWishList`

2023-02-20 08:22 UTC, Eli250 commented on src/database/models/productwishes.js
> +  class ProductWishes extends Model {
Rename class to `ProductWishList`

2023-02-20 08:22 UTC, Eli250 commented on src/database/seeders/20230216134243-ProductWishes.js
> +  async up (queryInterface, Sequelize) {
You have to provide at least 2 wishlist items here.

2023-02-20 08:22 UTC, Eli250 commented on src/middlewares/checkUserExist.js
> +import { User } from "../database/models/index";
I think we already have a middleware that checks this. If it is there, get rid of this file and use existing middleware.

2023-02-20 08:22 UTC, Eli250 commented on src/routes/api/product.route.js
> +route.get("/:id/product-wishes",
productWishList

2023-02-20 09:48 UTC, Ntarecedrick approved these changes

2023-02-20 09:56 UTC, Rutarenzi approved these changes

2023-02-20 10:04 UTC, NG-Solennel approved these changes

2023-02-20 12:07 UTC, Eli250 approved these changes

2023-02-20 12:08 UTC, merged